name: build

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
#          - ubuntu-latest
          - ubuntu-24.04
#          - ubuntu-22.04
#          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libao-dev libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev libcurl4-gnutls-dev libgcrypt20-dev libjson-c-dev libpth-dev pkg-config build-essential
      - name: Build pianobar
        run: make

  revert-change:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # check out the current and prior state
      - name: "Revert the commit that triggered this run"
        shell: bash
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert --no-edit ${{ github.sha }}
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
